---
- hosts: web
  become: yes
  tasks:
    - name: Install Apache Web Server
      apt:
        name: apache2
        state: present
      notify:
        - Start Apache

    - name: Copy index.html to Apache
      copy:
        src: ./index.html
        dest: /var/www/html/index.html

  handlers:
    - name: Start Apache
      service:
        name: apache2
        state: started

- hosts: db
  become: yes
  tasks:
    - name: Install MySQL Server
      apt:
        name: mysql-server
        state: present
      notify:
        - Start MySQL

  handlers:
    - name: Start MySQL
      service:
        name: mysql
        state: started
